
module.exports = {
  resource: '/photoEvent-sessions',
  path: '/photoEvent-sessions',
  httpMethod: 'POST',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'es-CO,es-419;q=0.9,es;q=0.8',
    Authorization: 'eyJraWQiOiJNa3hlNU4yYTEwMmowSVJTdndaMkNDSmxXV0RmWHF5eU5GdjhXVTFRdjBvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJmNjRjOTMzYy05MTZmLTRiZTgtOThjMy1mNWMwZGI3MDcxYWMiLCJjb2duaXRvOmdyb3VwcyI6WyJwaG90b2dyYXBoZXIiXSwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yX1ZDZDRNWjlYOCIsInBob25lX251bWJlcl92ZXJpZmllZCI6ZmFsc2UsImNvZ25pdG86dXNlcm5hbWUiOiJzZWJhc2NhcmRvbmFjMTEiLCJnaXZlbl9uYW1lIjoiU2ViYXN0aWFuIiwib3JpZ2luX2p0aSI6ImViZWYwZTFhLWY3MWYtNGQ4Yy05ZWMzLTI2ZmJjNmFhNDIyMyIsImNvZ25pdG86cm9sZXMiOlsiYXJuOmF3czppYW06OjU0Nzc0OTQ2MjgwMjpyb2xlXC9Db2duaXRvX3Bob3RvRXZlbnRBdXRoX1JvbGUiXSwiYXVkIjoidm0xc3AydTZnYzFndXY5aDJrNDN2ZDM0IiwiZXZlbnRfaWQiOiJjZGNlZWY4Zi0zYWNkLTRlNDgtYTE2Zi1iYmFkZmU3NmU1ZWMiLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY2MTE3ODQwMCwibmlja25hbWUiOiJzZWJhc2NhcmRvbmFjMTEiLCJwaG9uZV9udW1iZXIiOiIrNTczMTQ3MTM4NzY4IiwiZXhwIjoxNjYxOTE5OTEwLCJpYXQiOjE2NjE5MTYzMTAsImp0aSI6IjcxY2VhZjU3LTFhNDItNDA4YS1iNmZkLTlhNzQyMGY3MjIzNSIsImVtYWlsIjoic2ViYXNjYXJkb25hYzExQGdtYWlsLmNvbSJ9.JNZoQbArkloSQJhGXjBePEHQ4l0mnuAMpXd4OqtjQY7YOXvzOQWGUXZQxHPRNIxiCFe8GdFOhxZXxGGth-EKafzdI_bl3BX4__lI1ihla7HxU0YYLjlu_F8Zoh7qupq-ZkuPF5SuN9sFaKcDqDSxMr-YZTmo-nsfbDhUVXf7DcZroYASvQtjCUT0iv3HPO3lj2vsCGSCAqJTwqkgCy-J1DnFE7pXIirpCyGHWP9FBsn3K28uRHHGu3G1I_xtIxXVothdwJUe_HMCEBzzkBrWfhkZ6I3_6Za36eWt2IpNF1niZxBwGQ7z3siZbsmoDN7Z8BpOEeBXW1Wqwn4aADljvw',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-ASN': '10620',
    'CloudFront-Viewer-Country': 'CO',
    'content-type': 'application/json',
    Host: 'nw3ciel3qj.execute-api.us-east-2.amazonaws.com',
    origin: 'http://localhost:4200',
    Referer: 'http://localhost:4200/',
    'sec-ch-ua': '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'cross-site',
    'sec-gpc': '1',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',
    Via: '2.0 7d910156e52fe1536ffca93e93160cb2.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': 'S2tD2nktHugcS96eRWmdL0C6jRL_TPng-XIn1Ixzz5F2cSpjcc1SZA==',
    'X-Amzn-Trace-Id': 'Root=1-630edf6d-0c26e6f8597dc50a0a5c5d22',
    'X-Forwarded-For': '181.58.39.2, 64.252.186.161',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https'
  },
  multiValueHeaders: {
    Accept: [ 'application/json, text/plain, */*' ],
    'Accept-Encoding': [ 'gzip, deflate, br' ],
    'Accept-Language': [ 'es-CO,es-419;q=0.9,es;q=0.8' ],
    Authorization: [
      'eyJraWQiOiJNa3hlNU4yYTEwMmowSVJTdndaMkNDSmxXV0RmWHF5eU5GdjhXVTFRdjBvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJmNjRjOTMzYy05MTZmLTRiZTgtOThjMy1mNWMwZGI3MDcxYWMiLCJjb2duaXRvOmdyb3VwcyI6WyJwaG90b2dyYXBoZXIiXSwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yX1ZDZDRNWjlYOCIsInBob25lX251bWJlcl92ZXJpZmllZCI6ZmFsc2UsImNvZ25pdG86dXNlcm5hbWUiOiJzZWJhc2NhcmRvbmFjMTEiLCJnaXZlbl9uYW1lIjoiU2ViYXN0aWFuIiwib3JpZ2luX2p0aSI6ImViZWYwZTFhLWY3MWYtNGQ4Yy05ZWMzLTI2ZmJjNmFhNDIyMyIsImNvZ25pdG86cm9sZXMiOlsiYXJuOmF3czppYW06OjU0Nzc0OTQ2MjgwMjpyb2xlXC9Db2duaXRvX3Bob3RvRXZlbnRBdXRoX1JvbGUiXSwiYXVkIjoidm0xc3AydTZnYzFndXY5aDJrNDN2ZDM0IiwiZXZlbnRfaWQiOiJjZGNlZWY4Zi0zYWNkLTRlNDgtYTE2Zi1iYmFkZmU3NmU1ZWMiLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY2MTE3ODQwMCwibmlja25hbWUiOiJzZWJhc2NhcmRvbmFjMTEiLCJwaG9uZV9udW1iZXIiOiIrNTczMTQ3MTM4NzY4IiwiZXhwIjoxNjYxOTE5OTEwLCJpYXQiOjE2NjE5MTYzMTAsImp0aSI6IjcxY2VhZjU3LTFhNDItNDA4YS1iNmZkLTlhNzQyMGY3MjIzNSIsImVtYWlsIjoic2ViYXNjYXJkb25hYzExQGdtYWlsLmNvbSJ9.JNZoQbArkloSQJhGXjBePEHQ4l0mnuAMpXd4OqtjQY7YOXvzOQWGUXZQxHPRNIxiCFe8GdFOhxZXxGGth-EKafzdI_bl3BX4__lI1ihla7HxU0YYLjlu_F8Zoh7qupq-ZkuPF5SuN9sFaKcDqDSxMr-YZTmo-nsfbDhUVXf7DcZroYASvQtjCUT0iv3HPO3lj2vsCGSCAqJTwqkgCy-J1DnFE7pXIirpCyGHWP9FBsn3K28uRHHGu3G1I_xtIxXVothdwJUe_HMCEBzzkBrWfhkZ6I3_6Za36eWt2IpNF1niZxBwGQ7z3siZbsmoDN7Z8BpOEeBXW1Wqwn4aADljvw'
    ],
    'CloudFront-Forwarded-Proto': [ 'https' ],
    'CloudFront-Is-Desktop-Viewer': [ 'true' ],
    'CloudFront-Is-Mobile-Viewer': [ 'false' ],
    'CloudFront-Is-SmartTV-Viewer': [ 'false' ],
    'CloudFront-Is-Tablet-Viewer': [ 'false' ],
    'CloudFront-Viewer-ASN': [ '10620' ],
    'CloudFront-Viewer-Country': [ 'CO' ],
    'content-type': [ 'application/json' ],
    Host: [ 'nw3ciel3qj.execute-api.us-east-2.amazonaws.com' ],
    origin: [ 'http://localhost:4200' ],
    Referer: [ 'http://localhost:4200/' ],
    'sec-ch-ua': [
      '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"'
    ],
    'sec-ch-ua-mobile': [ '?0' ],
    'sec-ch-ua-platform': [ '"macOS"' ],
    'sec-fetch-dest': [ 'empty' ],
    'sec-fetch-mode': [ 'cors' ],
    'sec-fetch-site': [ 'cross-site' ],
    'sec-gpc': [ '1' ],
    'User-Agent': [
      'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36'
    ],
    Via: [
      '2.0 7d910156e52fe1536ffca93e93160cb2.cloudfront.net (CloudFront)'
    ],
    'X-Amz-Cf-Id': [ 'S2tD2nktHugcS96eRWmdL0C6jRL_TPng-XIn1Ixzz5F2cSpjcc1SZA==' ],
    'X-Amzn-Trace-Id': [ 'Root=1-630edf6d-0c26e6f8597dc50a0a5c5d22' ],
    'X-Forwarded-For': [ '181.58.39.2, 64.252.186.161' ],
    'X-Forwarded-Port': [ '443' ],
    'X-Forwarded-Proto': [ 'https' ]
  },
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 't1966q',
    authorizer: { claims: [Object] },
    resourcePath: '/photoEvent-sessions',
    httpMethod: 'POST',
    extendedRequestId: 'XtfZNFXtCYcF36A=',
    requestTime: '31/Aug/2022:04:11:25 +0000',
    path: '/dev/photoEvent-sessions',
    accountId: '547749462802',
    protocol: 'HTTP/1.1',
    stage: 'dev',
    domainPrefix: 'nw3ciel3qj',
    requestTimeEpoch: 1661919085906,
    requestId: 'b1385663-5dff-4144-92d3-eb62e0d46626',
    identity: {
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '181.58.39.2',
      principalOrgId: null,
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',
      user: null
    },
    domainName: 'nw3ciel3qj.execute-api.us-east-2.amazonaws.com',
    apiId: 'nw3ciel3qj'
  },
  body: '{"id":"10","name":"testSession","date":"2022-08-30","description":"Test"}',
  isBase64Encoded: false
}